---
title: "Portfolio assignment 1.2, part 2"
author: "Irene Schimmel"
date: "12-4-2021"
output: 
  html_document:
    code_folding: "hide"
---
##### H., I. Mental Health Impacts in Argentinean College Students During COVID-19 Quarantine https://osf.io/t523v/

##### J. The code mainly makes tables from the data and then runs several statistical analyses.

##### K. The code is very well readeable (4).

##### N. Line 11 asked for "clipboard" as input, but this didn't work. I fixed it by using the readxl library and importing dataset with that. 
##### All lines where a column name uses "." in between words need to be replaced with the column name with spaces.
##### The original code was put in lines: 13, 61, 64, 69, 72, 116, 135, 143, 144, 149
##### The first 150 lines were fixed.

##### O. Despite needing to change some of the code, the reproduction of a figure was rather easy (4).

##### P. 
###### Table 1; the transparency criteria.
|Transparency Criteria| Response|
|-------------|------|
|Study Purpose| Yes|
|Data Availability Statement| Yes|
|Data Location| Data Availability statement links to the OSF repository|
|Study Location| Yes, under "Method"|
|Author Review| Clear|
|Ethics Statement| Yes|
|Funding Statement| Yes|
|Code Availability| Yes|

***

```{r code for visualization, results="hide", warning=FALSE, message=FALSE}
# R Code for the manuscript entitled:
# "Mental health impacts in Argentinean college students during COVID-19 quarantine".
# López Steinmetz L.C., Leyes C.A., Dutto Florio M.A., Fong S.B., López Steinmetz R.L. & Godoy J.C.

##########################################################################
################## LOAD THE DATASET & PACKAGES ###########################
##########################################################################

library(readxl)

# Load the dataset
# table<-read.table("clipboard",header=TRUE, encoding = "Latin 1", dec=",", sep="\t") 
table <- read_excel("../data_raw/dataset.xlsx")
summary(table)

# Load the packages:
library(moments)
library(gplots)

##########################################################################
###################### METHODS ###########################################
##########################################################################

###### SUB-TITLE: METHOD > Sample and procedure
# SAMPLE N = 2687

# Distribution by sex:
table(table$SEX)
# Absolute frequencies: Women = 2192, Men = 473, Other = 22
prop.table(table(table$SEX))*100
# Percentages: Women = 81.577968%, Men = 17.603275%, Other = 0.818757%

# Central tendency measures by age (total sample)
# mean
mean(table$AGE)
# Mean age = 22.74023
# standard deviation
sd(table$AGE)
# sd age = 3.635612
# median
median(table$AGE)
# median age = 22

# Distribution by provinces
prop.table(table(table$PROVINCE))*100
# JUJ (JUJUY) = 6.6989207%
# SAL (SALTA) = 7.1082992%
# CBA (CÓRDOBA) = 39.0026051%
# STACR (SANTA CRUZ) = 0.9676219%
# TDELF (TIERRA DEL FUEGO) = 2.3446223%
# CABA (CIUDAD AUTÓNOMA DE BUENOS AIRES) = 11.9464086%
# PCIAB (PROVINCIA DE BUENOS AIRES) = 31.9315221%

###### SUB-TITLE: METHOD > Data analysis

### To test Skewness and Kurtosis # Criteria: range of acceptable values or near to (-3 and +3; Brown, 2006).
# Reference: Brown T.A. (2006). Confirmatory factor analysis for applied research. New York: Guilford Press.

# PSYCH.WELLBEING
# skewness(table$PSYCH.WELLBEING)
skewness(table$`PSYCH WELLBEING`)
# skewness PSYCH.WELLBEING = -0.05214941
# kurtosis(table$PSYCH.WELLBEING)
kurtosis(table$`PSYCH WELLBEING`)
# kurtosis PSYCH.WELLBEING = 1.951112

# SOC.FUNC.AND.COPING
# skewness(table$SOC.FUNC.AND.COPING)
skewness(table$`SOC FUNC AND COPING`)
# skewness SOC.FUNC.AND.COPING = 0.5326852
# kurtosis(table$SOC.FUNC.AND.COPING) 
kurtosis(table$`SOC FUNC AND COPING`)
# kurtosis SOC.FUNC.AND.COPING = 2.141538

# K10
skewness(table$K10) 
# skewness K10 = 0.2819622
kurtosis(table$K10)
# kurtosis K10 = 2.248409

# BDI
skewness(table$BDI) 
# skewness BDI = 0.6843361
kurtosis(table$BDI)
# kurtosis BDI = 2.907102

# STAIR
skewness(table$STAIR) 
# skewness STAIR =  0.02036605
kurtosis(table$STAIR)
# kurtosis STAIR = 2.336078

# YAACQ
skewness(table$YAACQ) 
# skewness YAACQ = 1.21683  
kurtosis(table$YAACQ)
# kurtosis YAACQ = 4.238449

# ISO30
skewness(table$ISO) 
# skewness ISO30 = 0.4657512
kurtosis(table$ISO)
# kurtosis ISO30 = 2.569562


### For analyses corresponding to the first aim, we divided the entire sample into four groups: 
table(table$REGIONS)
# NORTH = 371
# CENTER = 1048
# SOUTH = 89
# MOST POPULATED = 1179


### For analyses corresponding to the second aim, we divided the entire sample into four groups: 
#table(table$SUB.PERIODS.IN.PRE.AND.POST)
table(table$`SUB PERIODS IN PRE AND POST`)
# first week pre-quarantine extension (ONE WEEK PRE) = 1508
# second week pre-quarantine extension (TWO WEEK PRE) = 525
# first week post-quarantine extension (ONE WEEK POST) = 364
# remaining weeks post-quarantine extension (REMAINING WEEKS POST) = 290


##########################################################################
###################### RESULTS ###########################################
##########################################################################

##########################################################################
####################### AIM 1 ############################################
##########################################################################

### Differences in mental health aspects (both general and specific) by four regions

# PSYCHOLOGICAL WELL-BEING/DISCOMFORT (OF GENERAL HEALTH)
# anovaregpsychwellbeing <- aov(table$PSYCH.WELLBEING~table$REGIONS)
anovaregpsychwellbeing <- aov(table$`PSYCH WELLBEING`~table$REGIONS)
summary(anovaregpsychwellbeing)
plot(anovaregpsychwellbeing)
```
